import AppKit
import Combine
import CryptoKit

@MainActor
final class ClipboardService: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var isEnabled = true

    private var timer: Timer?
    private var lastChangeCount: Int
    /// Set while we write to the pasteboard ourselves, so re-copies don't duplicate entries.
    private var ignoreNextChange = false
    private let settings: SettingsStore
    private var saveTask: Task<Void, Never>?

    /// Apps and UTIs that ask, by convention, not to be recorded.
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping"
    ]

    init(settings: SettingsStore) {
        self.settings = settings
        self.lastChangeCount = NSPasteboard.general.changeCount
        load()
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        timer?.tolerance = 0.2
    }

    func stop() {
        timer?.invalidate(); timer = nil
    }

    func setEnabled(_ enabled: Bool) {
        isEnabled = enabled
        enabled ? start() : stop()
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if ignoreNextChange { ignoreNextChange = false; return }
        guard isEnabled else { return }

        let typeNames = Set((pasteboard.types ?? []).map(\.rawValue))
        guard typeNames.isDisjoint(with: Self.concealedTypes) else { return }

        let source = NSWorkspace.shared.frontmostApplication
        // Never record what Notchly itself put on the pasteboard.
        guard source?.bundleIdentifier != Bundle.main.bundleIdentifier else { return }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let kind: ClipboardItem.Kind
            if let url = URL(string: string.trimmingCharacters(in: .whitespacesAndNewlines)),
               let scheme = url.scheme, ["http", "https"].contains(scheme) {
                kind = .url
            } else if string.range(of: "^#[0-9A-Fa-f]{6}$", options: .regularExpression) != nil {
                kind = .color
            } else if typeNames.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
                kind = .file
            } else {
                kind = .text
            }
            insert(ClipboardItem(id: UUID(), kind: kind, text: string, imageFile: nil,
                                 createdAt: Date(), sourceBundleID: source?.bundleIdentifier,
                                 sourceName: source?.localizedName, isPinned: false,
                                 fingerprint: Self.digest(Data(string.utf8))))
            return
        }

        guard settings.settings.clipboardCapturesImages else { return }
        if let data = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png),
           let image = NSImage(data: data) {
            let fingerprint = Self.digest(data)
            guard !items.contains(where: { $0.fingerprint == fingerprint }) else { return }
            let name = "\(fingerprint).png"
            if let png = image.notchlyPNGData() {
                try? png.write(to: AppPaths.clipboardImagesDirectory.appendingPathComponent(name))
            }
            insert(ClipboardItem(id: UUID(), kind: .image, text: "", imageFile: name,
                                 createdAt: Date(), sourceBundleID: source?.bundleIdentifier,
                                 sourceName: source?.localizedName, isPinned: false,
                                 fingerprint: fingerprint))
        }
    }

    private func insert(_ item: ClipboardItem) {
        if let existing = items.firstIndex(where: { $0.fingerprint == item.fingerprint }) {
            // Promote the existing entry instead of stacking duplicates.
            var moved = items.remove(at: existing)
            moved.createdAt = item.createdAt
            items.insert(moved, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        scheduleSave()
    }

    private func trim() {
        let limit = max(20, settings.settings.clipboardHistoryLimit)
        guard items.count > limit else { return }
        let pinned = items.filter(\.isPinned)
        var unpinned = items.filter { !$0.isPinned }
        let overflow = unpinned.count - max(0, limit - pinned.count)
        if overflow > 0 {
            let dropped = unpinned.suffix(overflow)
            unpinned.removeLast(overflow)
            for item in dropped where item.kind == .image {
                if let file = item.imageFile {
                    try? FileManager.default.removeItem(at: AppPaths.clipboardImagesDirectory.appendingPathComponent(file))
                }
            }
        }
        items = (pinned + unpinned).sorted { lhs, rhs in
            if lhs.isPinned != rhs.isPinned { return lhs.isPinned }
            return lhs.createdAt > rhs.createdAt
        }
    }

    func copyToPasteboard(_ item: ClipboardItem) {
        ignoreNextChange = true
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.kind {
        case .image:
            if let file = item.imageFile,
               let image = NSImage(contentsOf: AppPaths.clipboardImagesDirectory.appendingPathComponent(file)) {
                pasteboard.writeObjects([image])
            }
        default:
            pasteboard.setString(item.text, forType: .string)
        }
        lastChangeCount = pasteboard.changeCount
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        trim()
        scheduleSave()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        if item.kind == .image, let file = item.imageFile {
            try? FileManager.default.removeItem(at: AppPaths.clipboardImagesDirectory.appendingPathComponent(file))
        }
        scheduleSave()
    }

    func clearAll(keepPinned: Bool = true) {
        let removed = items.filter { keepPinned ? !$0.isPinned : true }
        items = keepPinned ? items.filter(\.isPinned) : []
        for item in removed where item.kind == .image {
            if let file = item.imageFile {
                try? FileManager.default.removeItem(at: AppPaths.clipboardImagesDirectory.appendingPathComponent(file))
            }
        }
        scheduleSave()
    }

    func image(for item: ClipboardItem) -> NSImage? {
        guard let file = item.imageFile else { return nil }
        return NSImage(contentsOf: AppPaths.clipboardImagesDirectory.appendingPathComponent(file))
    }

    private func scheduleSave() {
        saveTask?.cancel()
        let snapshot = items
        saveTask = Task {
            try? await Task.sleep(for: .milliseconds(400))
            guard !Task.isCancelled else { return }
            let encoder = JSONEncoder()
            guard let data = try? encoder.encode(snapshot) else { return }
            try? data.write(to: AppPaths.clipboardStore, options: .atomic)
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: AppPaths.clipboardStore),
              let decoded = try? JSONDecoder().decode([ClipboardItem].self, from: data) else { return }
        items = decoded
    }

    private static func digest(_ data: Data) -> String {
        SHA256.hash(data: data).prefix(10).map { String(format: "%02x", $0) }.joined()
    }
}
